const express = require('express')
const app = express()
const cors = require('cors')
const mongoose = require('mongoose')
const fields = require('./routes/fields')
const users = require('./routes/users')
require('dotenv/config')
app.use(cors())
app.use(express.json())
app.use('/fields', fields)
app.use('/users', users)
mongoose.connect(process.env.dbLink, { useNewUrlParser: true, useUnifiedTopology: true }).then(res => console.log('connected to db')).catch(err => console.log(err))
app.listen(5000, () => console.log('server running on port 5000'))